name: Java Ubuntu 16 x64
on:
  push
jobs:
  bootstrap:
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
      - uses: actions/checkout@v3
      - name: Bootstrap Java
        run: ls -la
